#!/bin/bash

set -x -e

export DEBIAN_FRONTEND=noninteractive;

# Install apt packages, listed from "apt list --installed" on colab container
apt install -y qt5-default qt5-qmake-bin qt5-qmake qtbase5-dev-tools qtbase5-dev qtchooser r-base-core r-base-dev r-base r-cran-askpass r-cran-backports r-cran-base64enc r-cran-bit64 r-cran-bit r-cran-blob r-cran-boot r-cran-brew r-cran-brio r-cran-broom r-cran-bslib r-cran-cachem r-cran-callr r-cran-cellranger r-cran-class r-cran-cli r-cran-clipr r-cran-cluster r-cran-codetools r-cran-colorspace r-cran-commonmark r-cran-cpp11 r-cran-crayon r-cran-credentials r-cran-curl r-cran-data.table r-cran-dbi r-cran-dbplyr r-cran-desc r-cran-devtools r-cran-diffobj r-cran-digest r-cran-dplyr r-cran-dtplyr r-cran-ellipsis r-cran-evaluate r-cran-fansi r-cran-farver r-cran-fastmap r-cran-forcats r-cran-foreign r-cran-fs r-cran-gargle r-cran-generics r-cran-gert r-cran-ggplot2 r-cran-gh r-cran-gitcreds r-cran-glue r-cran-googledrive r-cran-googlesheets4 r-cran-gtable r-cran-haven r-cran-highr r-cran-hms r-cran-htmltools r-cran-httr2 r-cran-httr r-cran-ids r-cran-ini r-cran-isoband r-cran-jquerylib r-cran-jsonlite r-cran-kernsmooth r-cran-knitr r-cran-labeling r-cran-lattice r-cran-lifecycle r-cran-lubridate r-cran-magrittr r-cran-mass r-cran-matrix r-cran-memoise r-cran-mgcv r-cran-mime r-cran-modelr r-cran-munsell r-cran-nlme r-cran-nnet r-cran-openssl r-cran-pillar r-cran-pkgbuild r-cran-pkgconfig r-cran-pkgload r-cran-praise r-cran-prettyunits r-cran-processx r-cran-progress r-cran-ps r-cran-purrr r-cran-r6 r-cran-rappdirs r-cran-rcmdcheck r-cran-rcolorbrewer r-cran-readr r-cran-readxl r-cran-rematch2 r-cran-rematch r-cran-remotes r-cran-reprex r-cran-rlang r-cran-rmarkdown r-cran-roxygen2 r-cran-rpart r-cran-rprojroot r-cran-rstudioapi r-cran-rversions r-cran-rvest r-cran-sass r-cran-scales r-cran-selectr r-cran-sessioninfo r-cran-spatial r-cran-stringi r-cran-stringr r-cran-survival r-cran-svglite r-cran-sys r-cran-systemfonts r-cran-testthat r-cran-tibble r-cran-tidyr r-cran-tidyselect r-cran-tidyverse r-cran-timechange r-cran-tinytex r-cran-tzdb r-cran-usethis r-cran-utf8 r-cran-uuid r-cran-vctrs r-cran-viridislite r-cran-vroom r-cran-waldo r-cran-whisker r-cran-withr r-cran-xfun r-cran-xml2 r-cran-xopen r-cran-yaml r-cran-zip r-recommended readline-common rename rsync sed sensible-utils shared-mime-info software-properties-common sound-theme-freedesktop sudo systemd-sysv systemd-timesyncd systemd sysvinit-utils tar tcl-dev tcl8.6-dev tcl8.6 tcl tcllib tk-dev tk8.6-blt2.5 tk8.6-dev tk8.6 tk tmux tzdata ubuntu-keyring ubuntu-mono ucf unixodbc-dev unrar unzip util-linux uuid-dev vim-common vim-runtime vim wget x11-common x11proto-core-dev x11proto-dev x11proto-scrnsaver-dev x11proto-xext-dev xauth xdg-utils xkb-data xorg-sgml-doctools xsel xtrans-dev xxd xz-utils zip zlib1g-dev zlib1g
apt install -y python3-gdal python3-cairo python3-cairo-dev 
